/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dFxxUXvJK3H
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { ViolationContext } from "@/providers/ViolationProvider/ViolationProvider";
import { useRouter } from "next/navigation";
import { useContext } from "react";

export function TestViolationScreen() {
  const { violations } = useContext(ViolationContext);

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-gray-900 bg-opacity-90 z-50">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8 w-full max-w-md">
        <div className="space-y-4">
          <div className="text-center">
            <h1 className="text-3xl font-bold text-red-500">
              Violation Detected 🚨
            </h1>
            {/* Show the last violation code */}
            {violations.length > 0 && (
              <p className="text-gray-500 dark:text-gray-400 mt-2">
                {violations[violations.length - 1].code}
              </p>
            )}
            <p className="text-gray-500 dark:text-gray-400 mt-2">
              Our proctoring software has detected a violation of the exam
              rules.
            </p>
          </div>
          <div className="space-y-2">
            <h2 className="text-xl font-semibold">What Happened?</h2>
            <p className="text-gray-500 dark:text-gray-400">
              Our system detected unauthorized activity during the exam, such as
              attempting to access other applications or devices. This is a
              violation of the exam rules and could result in your exam being
              invalidated.
            </p>
          </div>
          <div className="space-y-2">
            <h2 className="text-xl font-semibold">Next Steps</h2>
            <p className="text-gray-500 dark:text-gray-400">
              Please remain calm and do not attempt to close or tamper with the
              proctoring software. A proctor will be in touch with you shortly
              to discuss the next steps. Depending on the severity of the
              violation, your exam may be invalidated or you may be given a
              chance to re-take the exam.
            </p>
          </div>
          <div className="text-center">
            <Button
              className="w-full"
              variant="outline"
              onClick={() => {
                location.reload();
              }}
            >
              Understood
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
