/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HQmrfB5LzS6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Skeleton } from "@/components/ui/skeleton";
import { div } from "@tensorflow/tfjs-node";

export function TestSkeletonScreen({ className }: { className?: string }) {
  return (
    <div className={`h-full grid place-items-center ${className}`}>
      <div className="flex flex-col items-center justify-center space-y-4 p-4 w-full">
        <Skeleton className="w-full max-w-3xl h-6" />
        <div className="flex justify-between w-full max-w-3xl">
          <Skeleton className="h-6 w-32" />
          <Skeleton className="h-6 w-32" />
        </div>
        <div className="flex justify-center w-full">
          <div className="flex space-x-2">
            <Skeleton className="w-10 h-10 rounded-full" />
            <Skeleton className="w-10 h-10 rounded-full" />
            <Skeleton className="w-10 h-10 rounded-full" />
            <Skeleton className="w-10 h-10 rounded-full" />
            <Skeleton className="w-10 h-10 rounded-full" />
          </div>
        </div>
        <div className="flex flex-col items-center space-y-2 w-full max-w-lg">
          <Skeleton className="w-full h-8" />
          <div className="flex justify-between w-full">
            <Skeleton className="h-6 w-24" />
            <Skeleton className="h-6 w-24" />
          </div>
          <Skeleton className="w-full h-4" />
          <Skeleton className="w-full h-4" />
          <Skeleton className="w-full h-4" />
          <Skeleton className="w-full h-4" />
        </div>
        <div className="flex space-x-4">
          <Skeleton className="h-10 w-24" />
          <Skeleton className="h-10 w-24" />
          <Skeleton className="h-10 w-24" />
        </div>
      </div>
    </div>
  );
}
